create database AlunosNotas;
use AlunosNotas;
create table Alunos(
	RA integer primary key auto_increment,
	nome varchar(40) not null,
	dataNasc date not null
	);
create table Notas(
	RA integer not null,
	disciplina varchar(15) not null,
	avaliacao varchar(10) not null,
	nota integer not null,
	constraint fkALuno foreign key (RA) references Alunos(RA)
	on delete cascade
	on update cascade
	);
	
insert into Alunos(nome,  dataNasc) values("Adelcio Biazi","2000/04/06");
insert into Alunos(nome,  dataNasc) values("Adriano da Silva Ferreira","2000/05/07");
insert into Alunos(nome,  dataNasc) values("Alisson Linhares de Carvalho","2000/06/13");
insert into Alunos(nome,  dataNasc) values("Amanda Cristina davi Resende","2000/07/14");
insert into Alunos(nome,  dataNasc) values("Ana Cláudia de Moura Laurentino","2000/08/15");
insert into Alunos(nome,  dataNasc) values("Ana Claudia Maciel","2000/09/16");
insert into Alunos(nome,  dataNasc) values("Argemiro Pentian Junior","2000/10/17");
insert into Alunos(nome,  dataNasc) values("Bento Rafael Siqueira","2000/02/18");
insert into Alunos(nome,  dataNasc) values("Bernardo Moreira Zabadal","2001/03/19");
insert into Alunos(nome,  dataNasc) values("Carlos Roberto de Oliveira Cazelatto Junior","2002/01/20");
insert into Alunos(nome,  dataNasc) values("Carlos Roberto Do Nascimento Costa","2000/03/21");
insert into Alunos(nome,  dataNasc) values("Cesar Augusto Pascali Rago","2002/12/22");
insert into Alunos(nome,  dataNasc) values("Claudemir de Souza Freitas Junior","2001/11/23");
insert into Alunos(nome,  dataNasc) values("Claudiane Mendes Trigueiro Silva","2000/10/24");
insert into Alunos(nome,  dataNasc) values("Claudiney Ramos Tinoco","2000/10/25");
insert into Alunos(nome,  dataNasc) values("Danilo César Pereira","2000/09/26");
insert into Alunos(nome,  dataNasc) values("Darvin Ames","2000/01/27");
insert into Alunos(nome,  dataNasc) values("Debora Barbosa Aires","2000/04/28");
insert into Alunos(nome,  dataNasc) values("Deivison Shindi Takatu","2000/05/01");
insert into Alunos(nome,  dataNasc) values("Denis Henrique Caixeta","2000/06/02");
insert into Alunos(nome,  dataNasc) values("Deysiane Matos Sande","2000/07/03");
insert into Alunos(nome,  dataNasc) values("Diego Rafael Moraes","2000/08/04");
insert into Alunos(nome,  dataNasc) values("Diogo Matos da Silva","2000/09/05");
insert into Alunos(nome,  dataNasc) values("Diogo Paulino da Cruz dos Santos","2000/10/14");
insert into Alunos(nome,  dataNasc) values("Douglas Brito damalio","2000/02/15");
insert into Alunos(nome,  dataNasc) values("Draylson Micael de Souza","2001/03/16");
insert into Alunos(nome,  dataNasc) values("Eder Almeida Batista de Oliveira","2002/01/17");
insert into Alunos(nome,  dataNasc) values("Ederlon Barbosa Cruz","2000/03/18");
insert into Alunos(nome,  dataNasc) values("Edinei Peres Legaspe","2002/12/08");
insert into Alunos(nome,  dataNasc) values("Ednei Jose de Almeida Junior","2001/11/09");
insert into Alunos(nome,  dataNasc) values("Eduardo de Paula Lima Nascimento","2000/10/10");
insert into Alunos(nome,  dataNasc) values("Eduardo Henrique Spies","2000/10/11");
insert into Alunos(nome,  dataNasc) values("Elaine Cecília Gatto","2000/09/12");
insert into Alunos(nome,  dataNasc) values("Elias Adriano Nogueira da Silva","2000/01/01");
insert into Alunos(nome,  dataNasc) values("Elis Cristina Montoro Hernandes Ervolino","2000/04/02");
insert into Alunos(nome,  dataNasc) values("Erica Aparecida Martins Siqueira","2000/05/03");
insert into Alunos(nome,  dataNasc) values("Erika Arias Barrado","2000/06/04");
insert into Alunos(nome,  dataNasc) values("Esteic Janaina Santos Batista","2000/07/05");
insert into Alunos(nome,  dataNasc) values("Everaldo Costa Silva Neto","2000/08/06");
insert into Alunos(nome,  dataNasc) values("Everaldo Silva de Freitas","2000/09/07");
insert into Alunos(nome,  dataNasc) values("Ewerton José da Silva","2000/10/13");
insert into Alunos(nome,  dataNasc) values("Fabio Luiz de Paula","2000/02/14");
insert into Alunos(nome,  dataNasc) values("Fabio Serafim","2001/03/15");
insert into Alunos(nome,  dataNasc) values("Felipe Gobo Bruno","2002/01/16");
insert into Alunos(nome,  dataNasc) values("Fernanda Zampieri Canaver","2000/03/17");
insert into Alunos(nome,  dataNasc) values("Fernando Claudio dos Santos Junior","2002/12/18");
insert into Alunos(nome,  dataNasc) values("Fernando Henrique Campos","2001/11/19");
insert into Alunos(nome,  dataNasc) values("Flávia Zenaro Nogueira E Silva","2000/10/20");
insert into Alunos(nome,  dataNasc) values("Floriano Ferreira dos Reis Filho","2000/10/21");
insert into Alunos(nome,  dataNasc) values("Frances Albert Santos","2000/09/22");
insert into Alunos(nome,  dataNasc) values("Francisco Assis da Silva","2000/01/23");
insert into Alunos(nome,  dataNasc) values("Francisco Edigleison da Silva Barbosa","2000/04/24");
insert into Alunos(nome,  dataNasc) values("Francisco José Nardi Filho","2000/05/25");
insert into Alunos(nome,  dataNasc) values("Gabriel Ferreira Teles Gomes","2000/06/26");
insert into Alunos(nome,  dataNasc) values("Gabriel Morais Silveira","2000/07/27");
insert into Alunos(nome,  dataNasc) values("Gabriel Sgorlon Tininis","2000/08/28");
insert into Alunos(nome,  dataNasc) values("Gabriel Spadon de Souza","2000/09/01");
insert into Alunos(nome,  dataNasc) values("Gerson Luiz Camillo","2000/10/02");
insert into Alunos(nome,  dataNasc) values("Giovani Bertolla Sampaio","2000/02/03");
insert into Alunos(nome,  dataNasc) values("Giovanna Nascimento Antonieti","2001/03/04");
insert into Alunos(nome,  dataNasc) values("Gustavo Moreira Calixto","2002/01/05");
insert into Alunos(nome,  dataNasc) values("Helder Pestana","2000/03/14");
insert into Alunos(nome,  dataNasc) values("Hiago Araujo Silva","2002/12/15");
insert into Alunos(nome,  dataNasc) values("Higor Antonio delsoto","2001/11/16");
insert into Alunos(nome,  dataNasc) values("Icaro Cavalcante Dourado","2000/10/17");
insert into Alunos(nome,  dataNasc) values("Ingrid Marçal","2000/10/18");
insert into Alunos(nome,  dataNasc) values("Jeane Aparecida Menegueli","2000/09/11");
insert into Alunos(nome,  dataNasc) values("Jefferson Barbosa Belo da Silva","2000/01/12");
insert into Alunos(nome,  dataNasc) values("Jefferson Carlos Pedroso","2000/04/01");
insert into Alunos(nome,  dataNasc) values("Jessé Italo Silva","2000/05/02");
insert into Alunos(nome,  dataNasc) values("José Eugênio de Mira","2000/06/03");
insert into Alunos(nome,  dataNasc) values("José Rafael Pilan","2000/07/04");
insert into Alunos(nome,  dataNasc) values("José Renato Paviotti","2000/08/05");
insert into Alunos(nome,  dataNasc) values("José Santiago Moreira de Mello","2000/09/06");
insert into Alunos(nome,  dataNasc) values("Josiane Rosa de Oliveira Gaia Pimenta","2000/10/07");
insert into Alunos(nome,  dataNasc) values("Juliana de Sousa Ribeiro","2000/01/13");
insert into Alunos(nome,  dataNasc) values("Liliam Sayuri Sakamoto","2000/04/14");
insert into Alunos(nome,  dataNasc) values("Lucas Hermann Negri","2000/05/15");
insert into Alunos(nome,  dataNasc) values("Luciano Rossi","2000/06/16");
insert into Alunos(nome,  dataNasc) values("Luciano Rovanni Do Nascimento","2000/07/17");
insert into Alunos(nome,  dataNasc) values("Marcelo Do Carmo Vieira Scomparim","2000/08/18");
insert into Alunos(nome,  dataNasc) values("Marcelo José Vigorito Campara","2000/09/19");
insert into Alunos(nome,  dataNasc) values("Murilo Gleyson Gazzola","2000/10/20");
insert into Alunos(nome,  dataNasc) values("Ovídio José Francisco","2000/02/21");
insert into Alunos(nome,  dataNasc) values("Patrícia Fernanda da Silva Freitas","2001/03/22");
insert into Alunos(nome,  dataNasc) values("Paula Leticia Santos Lima","2002/01/23");
insert into Alunos(nome,  dataNasc) values("Rafael Tomé de Souza","2000/03/24");
insert into Alunos(nome,  dataNasc) values("Rafaela de Jesus Alencar","2002/12/25");
insert into Alunos(nome,  dataNasc) values("Ramon Simões Abílio","2000/02/08");
insert into Alunos(nome,  dataNasc) values("Raphael Hungaro Moretti","2001/03/09");
insert into Alunos(nome,  dataNasc) values("Sara Luzia de Melo","2002/01/10");
insert into Alunos(nome,  dataNasc) values("Sergio Willians Poneli","2000/03/11");
insert into Alunos(nome,  dataNasc) values("Silvia Roberta de Jesus Garcia","2002/12/12");
insert into Alunos(nome,  dataNasc) values("Suéllen Rodolfo Martinelli","2001/11/01");
insert into Alunos(nome,  dataNasc) values("Taynara Cerigueli Dutra","2000/10/02");
insert into Alunos(nome,  dataNasc) values("Thamires de Campos Luz","2000/10/03");
insert into Alunos(nome,  dataNasc) values("Viviane Mello Bonadia dos Santos","2000/09/04");
insert into Alunos(nome,  dataNasc) values("Walter Paulo Costenaro","2000/01/05");
insert into Alunos(nome,  dataNasc) values("Wellington Fabio de Oliveira Martins","2001/11/26");
insert into Alunos(nome,  dataNasc) values("André Luyde da Silva Souza","2000/10/27");
insert into Alunos(nome,  dataNasc) values("Anisio Alfredo da Silva Junior","2000/10/28");
insert into Alunos(nome,  dataNasc) values("Carlos César Farias de Souza","2000/09/01");
insert into Alunos(nome,  dataNasc) values("Dyogo Porfirio Almeida Santos","2000/01/02");
insert into Alunos(nome,  dataNasc) values("Edinilson da Silva Vida","2000/04/03");
insert into Alunos(nome,  dataNasc) values("Everton Jose de Souza","2000/05/04");

insert into Notas(RA, disciplina, avaliacao, nota) values(1,"Banco de Dados","Trabalhos",50);
insert into Notas(RA, disciplina, avaliacao, nota) values(1,"Banco de Dados","Somativa1",43);
insert into Notas(RA, disciplina, avaliacao, nota) values(1,"Programação Mobile","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(1,"Programação Mobile","Somativa2",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(1,"Programação Web","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(1,"Programação Web","Somativa2",92);
insert into Notas(RA, disciplina, avaliacao, nota) values(2,"Banco de Dados","Trabalhos",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(2,"Banco de Dados","Somativa1",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(2,"Programação Mobile","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(2,"Programação Mobile","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(2,"Programação Web","Somativa1",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(2,"Programação Web","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(3,"Banco de Dados","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(3,"Banco de Dados","Somativa1",42);
insert into Notas(RA, disciplina, avaliacao, nota) values(3,"Programação Mobile","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(3,"Programação Mobile","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(3,"Programação Web","Somativa1",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(3,"Programação Web","Somativa2",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(4,"Banco de Dados","Trabalhos",25);
insert into Notas(RA, disciplina, avaliacao, nota) values(4,"Banco de Dados","Somativa1",41);
insert into Notas(RA, disciplina, avaliacao, nota) values(4,"Programação Mobile","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(4,"Programação Mobile","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(4,"Programação Web","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(4,"Programação Web","Somativa2",77);
insert into Notas(RA, disciplina, avaliacao, nota) values(5,"Banco de Dados","Trabalhos",5);
insert into Notas(RA, disciplina, avaliacao, nota) values(5,"Banco de Dados","Somativa1",49);
insert into Notas(RA, disciplina, avaliacao, nota) values(5,"Programação Mobile","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(5,"Programação Mobile","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(5,"Programação Web","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(5,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(6,"Banco de Dados","Trabalhos",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(6,"Banco de Dados","Somativa1",50);
insert into Notas(RA, disciplina, avaliacao, nota) values(6,"Programação Mobile","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(6,"Programação Mobile","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(6,"Programação Web","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(6,"Programação Web","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(7,"Banco de Dados","Trabalhos",25);
insert into Notas(RA, disciplina, avaliacao, nota) values(7,"Banco de Dados","Somativa1",51);
insert into Notas(RA, disciplina, avaliacao, nota) values(7,"Programação Mobile","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(7,"Programação Mobile","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(7,"Programação Web","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(7,"Programação Web","Somativa2",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(8,"Banco de Dados","Trabalhos",35);
insert into Notas(RA, disciplina, avaliacao, nota) values(8,"Banco de Dados","Somativa1",52);
insert into Notas(RA, disciplina, avaliacao, nota) values(8,"Programação Mobile","Somativa1",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(8,"Programação Mobile","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(8,"Programação Web","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(8,"Programação Web","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(9,"Banco de Dados","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(9,"Banco de Dados","Somativa1",53);
insert into Notas(RA, disciplina, avaliacao, nota) values(9,"Programação Mobile","Somativa1",99);
insert into Notas(RA, disciplina, avaliacao, nota) values(9,"Programação Mobile","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(9,"Programação Web","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(9,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(10,"Banco de Dados","Trabalhos",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(10,"Banco de Dados","Somativa1",54);
insert into Notas(RA, disciplina, avaliacao, nota) values(10,"Programação Mobile","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(10,"Programação Mobile","Somativa2",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(10,"Programação Web","Somativa1",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(10,"Programação Web","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(11,"Banco de Dados","Trabalhos",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(11,"Banco de Dados","Somativa1",57);
insert into Notas(RA, disciplina, avaliacao, nota) values(11,"Programação Mobile","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(11,"Programação Mobile","Somativa2",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(11,"Programação Web","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(11,"Programação Web","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(12,"Banco de Dados","Trabalhos",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(12,"Banco de Dados","Somativa1",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(12,"Programação Mobile","Somativa1",92);
insert into Notas(RA, disciplina, avaliacao, nota) values(12,"Programação Mobile","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(12,"Programação Web","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(12,"Programação Web","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(13,"Banco de Dados","Trabalhos",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(13,"Banco de Dados","Somativa1",56);
insert into Notas(RA, disciplina, avaliacao, nota) values(13,"Programação Mobile","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(13,"Programação Mobile","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(13,"Programação Web","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(13,"Programação Web","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(14,"Banco de Dados","Trabalhos",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(14,"Banco de Dados","Somativa1",58);
insert into Notas(RA, disciplina, avaliacao, nota) values(14,"Programação Mobile","Somativa1",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(14,"Programação Mobile","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(14,"Programação Web","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(14,"Programação Web","Somativa2",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(15,"Banco de Dados","Trabalhos",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(15,"Banco de Dados","Somativa1",57);
insert into Notas(RA, disciplina, avaliacao, nota) values(15,"Programação Mobile","Somativa1",77);
insert into Notas(RA, disciplina, avaliacao, nota) values(15,"Programação Mobile","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(15,"Programação Web","Somativa1",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(15,"Programação Web","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(16,"Banco de Dados","Trabalhos",28);
insert into Notas(RA, disciplina, avaliacao, nota) values(16,"Banco de Dados","Somativa1",1);
insert into Notas(RA, disciplina, avaliacao, nota) values(16,"Programação Mobile","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(16,"Programação Mobile","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(16,"Programação Web","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(16,"Programação Web","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(17,"Banco de Dados","Trabalhos",29);
insert into Notas(RA, disciplina, avaliacao, nota) values(17,"Banco de Dados","Somativa1",54);
insert into Notas(RA, disciplina, avaliacao, nota) values(17,"Programação Mobile","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(17,"Programação Mobile","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(17,"Programação Web","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(17,"Programação Web","Somativa2",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(18,"Banco de Dados","Trabalhos",35);
insert into Notas(RA, disciplina, avaliacao, nota) values(18,"Banco de Dados","Somativa1",58);
insert into Notas(RA, disciplina, avaliacao, nota) values(18,"Programação Mobile","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(18,"Programação Mobile","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(18,"Programação Web","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(18,"Programação Web","Somativa2",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(19,"Banco de Dados","Trabalhos",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(19,"Banco de Dados","Somativa1",2);
insert into Notas(RA, disciplina, avaliacao, nota) values(19,"Programação Mobile","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(19,"Programação Mobile","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(19,"Programação Web","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(19,"Programação Web","Somativa2",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(20,"Banco de Dados","Trabalhos",78);
insert into Notas(RA, disciplina, avaliacao, nota) values(20,"Banco de Dados","Somativa1",31);
insert into Notas(RA, disciplina, avaliacao, nota) values(20,"Programação Mobile","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(20,"Programação Mobile","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(20,"Programação Web","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(20,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(21,"Banco de Dados","Trabalhos",89);
insert into Notas(RA, disciplina, avaliacao, nota) values(21,"Banco de Dados","Somativa1",32);
insert into Notas(RA, disciplina, avaliacao, nota) values(21,"Programação Mobile","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(21,"Programação Mobile","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(21,"Programação Web","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(21,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(22,"Banco de Dados","Trabalhos",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(22,"Banco de Dados","Somativa1",33);
insert into Notas(RA, disciplina, avaliacao, nota) values(22,"Programação Mobile","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(22,"Programação Mobile","Somativa2",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(22,"Programação Web","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(22,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(23,"Banco de Dados","Trabalhos",99);
insert into Notas(RA, disciplina, avaliacao, nota) values(23,"Banco de Dados","Somativa1",3);
insert into Notas(RA, disciplina, avaliacao, nota) values(23,"Programação Mobile","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(23,"Programação Mobile","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(23,"Programação Web","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(23,"Programação Web","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(24,"Banco de Dados","Trabalhos",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(24,"Banco de Dados","Somativa1",44);
insert into Notas(RA, disciplina, avaliacao, nota) values(24,"Programação Mobile","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(24,"Programação Mobile","Somativa2",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(24,"Programação Web","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(24,"Programação Web","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(25,"Banco de Dados","Trabalhos",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(25,"Banco de Dados","Somativa1",4);
insert into Notas(RA, disciplina, avaliacao, nota) values(25,"Programação Mobile","Somativa1",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(25,"Programação Mobile","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(25,"Programação Web","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(25,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(26,"Banco de Dados","Trabalhos",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(26,"Banco de Dados","Somativa1",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(26,"Programação Mobile","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(26,"Programação Mobile","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(26,"Programação Web","Somativa1",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(26,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(27,"Banco de Dados","Trabalhos",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(27,"Banco de Dados","Somativa1",5);
insert into Notas(RA, disciplina, avaliacao, nota) values(27,"Programação Mobile","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(27,"Programação Mobile","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(27,"Programação Web","Somativa1",99);
insert into Notas(RA, disciplina, avaliacao, nota) values(27,"Programação Web","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(28,"Banco de Dados","Trabalhos",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(28,"Banco de Dados","Somativa1",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(28,"Programação Mobile","Somativa1",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(28,"Programação Mobile","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(28,"Programação Web","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(28,"Programação Web","Somativa2",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(29,"Banco de Dados","Trabalhos",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(29,"Banco de Dados","Somativa1",6);
insert into Notas(RA, disciplina, avaliacao, nota) values(29,"Programação Mobile","Somativa1",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(29,"Programação Mobile","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(29,"Programação Web","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(29,"Programação Web","Somativa2",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(30,"Banco de Dados","Trabalhos",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(30,"Banco de Dados","Somativa1",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(30,"Programação Mobile","Somativa1",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(30,"Programação Mobile","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(30,"Programação Web","Somativa1",92);
insert into Notas(RA, disciplina, avaliacao, nota) values(30,"Programação Web","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(31,"Eletrônica Analógica","Somativa1",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(31,"Eletrônica Analógica","Somativa2",7);
insert into Notas(RA, disciplina, avaliacao, nota) values(31,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(31,"Eletrônica Digital","Somativa1",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(31,"Princípios da Eletricidade","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(31,"Princípios da Eletricidade","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(32,"Eletrônica Analógica","Somativa1",89);
insert into Notas(RA, disciplina, avaliacao, nota) values(32,"Eletrônica Analógica","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(32,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(32,"Eletrônica Digital","Somativa1",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(32,"Princípios da Eletricidade","Somativa1",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(32,"Princípios da Eletricidade","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(33,"Eletrônica Analógica","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(33,"Eletrônica Analógica","Somativa2",8);
insert into Notas(RA, disciplina, avaliacao, nota) values(33,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(33,"Eletrônica Digital","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(33,"Princípios da Eletricidade","Somativa1",77);
insert into Notas(RA, disciplina, avaliacao, nota) values(33,"Princípios da Eletricidade","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(34,"Eletrônica Analógica","Somativa1",91);
insert into Notas(RA, disciplina, avaliacao, nota) values(34,"Eletrônica Analógica","Somativa2",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(34,"Eletrônica Digital","Trabalhos",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(34,"Eletrônica Digital","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(34,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(34,"Princípios da Eletricidade","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(35,"Eletrônica Analógica","Somativa1",92);
insert into Notas(RA, disciplina, avaliacao, nota) values(35,"Eletrônica Analógica","Somativa2",9);
insert into Notas(RA, disciplina, avaliacao, nota) values(35,"Eletrônica Digital","Trabalhos",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(35,"Eletrônica Digital","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(35,"Princípios da Eletricidade","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(35,"Princípios da Eletricidade","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(36,"Eletrônica Analógica","Somativa1",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(36,"Eletrônica Analógica","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(36,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(36,"Eletrônica Digital","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(36,"Princípios da Eletricidade","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(36,"Princípios da Eletricidade","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(37,"Eletrônica Analógica","Somativa1",56);
insert into Notas(RA, disciplina, avaliacao, nota) values(37,"Eletrônica Analógica","Somativa2",10);
insert into Notas(RA, disciplina, avaliacao, nota) values(37,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(37,"Eletrônica Digital","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(37,"Princípios da Eletricidade","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(37,"Princípios da Eletricidade","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(38,"Eletrônica Analógica","Somativa1",58);
insert into Notas(RA, disciplina, avaliacao, nota) values(38,"Eletrônica Analógica","Somativa2",11);
insert into Notas(RA, disciplina, avaliacao, nota) values(38,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(38,"Eletrônica Digital","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(38,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(38,"Princípios da Eletricidade","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(39,"Eletrônica Analógica","Somativa1",57);
insert into Notas(RA, disciplina, avaliacao, nota) values(39,"Eletrônica Analógica","Somativa2",20);
insert into Notas(RA, disciplina, avaliacao, nota) values(39,"Eletrônica Digital","Trabalhos",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(39,"Eletrônica Digital","Somativa1",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(39,"Princípios da Eletricidade","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(39,"Princípios da Eletricidade","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(40,"Eletrônica Analógica","Somativa1",59);
insert into Notas(RA, disciplina, avaliacao, nota) values(40,"Eletrônica Analógica","Somativa2",19);
insert into Notas(RA, disciplina, avaliacao, nota) values(40,"Eletrônica Digital","Trabalhos",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(40,"Eletrônica Digital","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(40,"Princípios da Eletricidade","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(40,"Princípios da Eletricidade","Somativa2",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(41,"Eletrônica Analógica","Somativa1",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(41,"Eletrônica Analógica","Somativa2",18);
insert into Notas(RA, disciplina, avaliacao, nota) values(41,"Eletrônica Digital","Trabalhos",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(41,"Eletrônica Digital","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(41,"Princípios da Eletricidade","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(41,"Princípios da Eletricidade","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(42,"Eletrônica Analógica","Somativa1",62);
insert into Notas(RA, disciplina, avaliacao, nota) values(42,"Eletrônica Analógica","Somativa2",18);
insert into Notas(RA, disciplina, avaliacao, nota) values(42,"Eletrônica Digital","Trabalhos",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(42,"Eletrônica Digital","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(42,"Princípios da Eletricidade","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(42,"Princípios da Eletricidade","Somativa2",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(43,"Eletrônica Analógica","Somativa1",61);
insert into Notas(RA, disciplina, avaliacao, nota) values(43,"Eletrônica Analógica","Somativa2",17);
insert into Notas(RA, disciplina, avaliacao, nota) values(43,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(43,"Eletrônica Digital","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(43,"Princípios da Eletricidade","Somativa1",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(43,"Princípios da Eletricidade","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(44,"Eletrônica Analógica","Somativa1",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(44,"Eletrônica Analógica","Somativa2",19);
insert into Notas(RA, disciplina, avaliacao, nota) values(44,"Eletrônica Digital","Trabalhos",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(44,"Eletrônica Digital","Somativa1",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(44,"Princípios da Eletricidade","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(44,"Princípios da Eletricidade","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(45,"Eletrônica Analógica","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(45,"Eletrônica Analógica","Somativa2",16);
insert into Notas(RA, disciplina, avaliacao, nota) values(45,"Eletrônica Digital","Trabalhos",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(45,"Eletrônica Digital","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(45,"Princípios da Eletricidade","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(45,"Princípios da Eletricidade","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(46,"Eletrônica Analógica","Somativa1",71);
insert into Notas(RA, disciplina, avaliacao, nota) values(46,"Eletrônica Analógica","Somativa2",16);
insert into Notas(RA, disciplina, avaliacao, nota) values(46,"Eletrônica Digital","Trabalhos",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(46,"Eletrônica Digital","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(46,"Princípios da Eletricidade","Somativa1",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(46,"Princípios da Eletricidade","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(47,"Eletrônica Analógica","Somativa1",72);
insert into Notas(RA, disciplina, avaliacao, nota) values(47,"Eletrônica Analógica","Somativa2",15);
insert into Notas(RA, disciplina, avaliacao, nota) values(47,"Eletrônica Digital","Trabalhos",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(47,"Eletrônica Digital","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(47,"Princípios da Eletricidade","Somativa1",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(47,"Princípios da Eletricidade","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(48,"Eletrônica Analógica","Somativa1",73);
insert into Notas(RA, disciplina, avaliacao, nota) values(48,"Eletrônica Analógica","Somativa2",14);
insert into Notas(RA, disciplina, avaliacao, nota) values(48,"Eletrônica Digital","Trabalhos",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(48,"Eletrônica Digital","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(48,"Princípios da Eletricidade","Somativa1",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(48,"Princípios da Eletricidade","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(49,"Eletrônica Analógica","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(49,"Eletrônica Analógica","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(49,"Eletrônica Digital","Trabalhos",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(49,"Eletrônica Digital","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(49,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(49,"Princípios da Eletricidade","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(50,"Eletrônica Analógica","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(50,"Eletrônica Analógica","Somativa2",12);
insert into Notas(RA, disciplina, avaliacao, nota) values(50,"Eletrônica Digital","Trabalhos",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(50,"Eletrônica Digital","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(50,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(50,"Princípios da Eletricidade","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(51,"Eletrônica Analógica","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(51,"Eletrônica Analógica","Somativa2",11);
insert into Notas(RA, disciplina, avaliacao, nota) values(51,"Eletrônica Digital","Trabalhos",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(51,"Eletrônica Digital","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(51,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(51,"Princípios da Eletricidade","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(52,"Eletrônica Analógica","Somativa1",76);
insert into Notas(RA, disciplina, avaliacao, nota) values(52,"Eletrônica Analógica","Somativa2",10);
insert into Notas(RA, disciplina, avaliacao, nota) values(52,"Eletrônica Digital","Trabalhos",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(52,"Eletrônica Digital","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(52,"Princípios da Eletricidade","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(52,"Princípios da Eletricidade","Somativa2",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(53,"Eletrônica Analógica","Somativa1",78);
insert into Notas(RA, disciplina, avaliacao, nota) values(53,"Eletrônica Analógica","Somativa2",10);
insert into Notas(RA, disciplina, avaliacao, nota) values(53,"Eletrônica Digital","Trabalhos",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(53,"Eletrônica Digital","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(53,"Princípios da Eletricidade","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(53,"Princípios da Eletricidade","Somativa2",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(54,"Eletrônica Analógica","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(54,"Eletrônica Analógica","Somativa2",21);
insert into Notas(RA, disciplina, avaliacao, nota) values(54,"Eletrônica Digital","Trabalhos",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(54,"Eletrônica Digital","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(54,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(54,"Princípios da Eletricidade","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(55,"Eletrônica Analógica","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(55,"Eletrônica Analógica","Somativa2",22);
insert into Notas(RA, disciplina, avaliacao, nota) values(55,"Eletrônica Digital","Trabalhos",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(55,"Eletrônica Digital","Somativa1",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(55,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(55,"Princípios da Eletricidade","Somativa2",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(56,"Eletrônica Analógica","Somativa1",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(56,"Eletrônica Analógica","Somativa2",23);
insert into Notas(RA, disciplina, avaliacao, nota) values(56,"Eletrônica Digital","Trabalhos",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(56,"Eletrônica Digital","Somativa1",99);
insert into Notas(RA, disciplina, avaliacao, nota) values(56,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(56,"Princípios da Eletricidade","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(57,"Eletrônica Analógica","Somativa1",82);
insert into Notas(RA, disciplina, avaliacao, nota) values(57,"Eletrônica Analógica","Somativa2",24);
insert into Notas(RA, disciplina, avaliacao, nota) values(57,"Eletrônica Digital","Trabalhos",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(57,"Eletrônica Digital","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(57,"Princípios da Eletricidade","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(57,"Princípios da Eletricidade","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(58,"Eletrônica Analógica","Somativa1",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(58,"Eletrônica Analógica","Somativa2",25);
insert into Notas(RA, disciplina, avaliacao, nota) values(58,"Eletrônica Digital","Trabalhos",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(58,"Eletrônica Digital","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(58,"Princípios da Eletricidade","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(58,"Princípios da Eletricidade","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(59,"Eletrônica Analógica","Somativa1",83);
insert into Notas(RA, disciplina, avaliacao, nota) values(59,"Eletrônica Analógica","Somativa2",26);
insert into Notas(RA, disciplina, avaliacao, nota) values(59,"Eletrônica Digital","Trabalhos",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(59,"Eletrônica Digital","Somativa1",92);
insert into Notas(RA, disciplina, avaliacao, nota) values(59,"Princípios da Eletricidade","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(59,"Princípios da Eletricidade","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(60,"Eletrônica Analógica","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(60,"Eletrônica Analógica","Somativa2",27);
insert into Notas(RA, disciplina, avaliacao, nota) values(60,"Eletrônica Digital","Trabalhos",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(60,"Eletrônica Digital","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(60,"Princípios da Eletricidade","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(60,"Princípios da Eletricidade","Somativa2",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(61,"Eletrônica Analógica","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(61,"Eletrônica Analógica","Somativa2",28);
insert into Notas(RA, disciplina, avaliacao, nota) values(61,"Eletrônica Digital","Trabalhos",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(61,"Eletrônica Digital","Somativa1",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(61,"Princípios da Eletricidade","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(61,"Princípios da Eletricidade","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(62,"Eletrônica Analógica","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(62,"Eletrônica Analógica","Somativa2",29);
insert into Notas(RA, disciplina, avaliacao, nota) values(62,"Eletrônica Digital","Trabalhos",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(62,"Eletrônica Digital","Somativa1",77);
insert into Notas(RA, disciplina, avaliacao, nota) values(62,"Princípios da Eletricidade","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(62,"Princípios da Eletricidade","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(63,"Eletrônica Analógica","Somativa1",86);
insert into Notas(RA, disciplina, avaliacao, nota) values(63,"Eletrônica Analógica","Somativa2",30);
insert into Notas(RA, disciplina, avaliacao, nota) values(63,"Eletrônica Digital","Trabalhos",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(63,"Eletrônica Digital","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(63,"Princípios da Eletricidade","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(63,"Princípios da Eletricidade","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(64,"Eletrônica Analógica","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(64,"Eletrônica Analógica","Somativa2",49);
insert into Notas(RA, disciplina, avaliacao, nota) values(64,"Eletrônica Digital","Trabalhos",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(64,"Eletrônica Digital","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(64,"Princípios da Eletricidade","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(64,"Princípios da Eletricidade","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(65,"Eletrônica Analógica","Somativa1",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(65,"Eletrônica Analógica","Somativa2",48);
insert into Notas(RA, disciplina, avaliacao, nota) values(65,"Eletrônica Digital","Trabalhos",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(65,"Eletrônica Digital","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(65,"Princípios da Eletricidade","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(65,"Princípios da Eletricidade","Somativa2",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(66,"Eletrônica Analógica","Somativa1",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(66,"Eletrônica Analógica","Somativa2",47);
insert into Notas(RA, disciplina, avaliacao, nota) values(66,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(66,"Eletrônica Digital","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(66,"Princípios da Eletricidade","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(66,"Princípios da Eletricidade","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(67,"Eletrônica Analógica","Somativa1",89);
insert into Notas(RA, disciplina, avaliacao, nota) values(67,"Eletrônica Analógica","Somativa2",46);
insert into Notas(RA, disciplina, avaliacao, nota) values(67,"Eletrônica Digital","Trabalhos",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(67,"Eletrônica Digital","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(67,"Princípios da Eletricidade","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(67,"Princípios da Eletricidade","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(68,"Eletrônica Analógica","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(68,"Eletrônica Analógica","Somativa2",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(68,"Eletrônica Digital","Trabalhos",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(68,"Eletrônica Digital","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(68,"Princípios da Eletricidade","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(68,"Princípios da Eletricidade","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(69,"Eletrônica Analógica","Somativa1",51);
insert into Notas(RA, disciplina, avaliacao, nota) values(69,"Eletrônica Analógica","Somativa2",44);
insert into Notas(RA, disciplina, avaliacao, nota) values(69,"Eletrônica Digital","Trabalhos",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(69,"Eletrônica Digital","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(69,"Princípios da Eletricidade","Somativa1",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(69,"Princípios da Eletricidade","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(70,"Eletrônica Analógica","Somativa1",50);
insert into Notas(RA, disciplina, avaliacao, nota) values(70,"Eletrônica Analógica","Somativa2",43);
insert into Notas(RA, disciplina, avaliacao, nota) values(70,"Eletrônica Digital","Trabalhos",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(70,"Eletrônica Digital","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(70,"Princípios da Eletricidade","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(70,"Princípios da Eletricidade","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(71,"Automação Indústrial","Somativa1",52);
insert into Notas(RA, disciplina, avaliacao, nota) values(71,"Automação Indústrial","Somativa2",42);
insert into Notas(RA, disciplina, avaliacao, nota) values(71,"Dinâmica dos Fluídos","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(71,"Dinâmica dos Fluídos","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(71,"Desenho Técnico","Somativa1",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(71,"Desenho Técnico","Somativa2",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(72,"Automação Indústrial","Somativa1",53);
insert into Notas(RA, disciplina, avaliacao, nota) values(72,"Automação Indústrial","Somativa2",41);
insert into Notas(RA, disciplina, avaliacao, nota) values(72,"Dinâmica dos Fluídos","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(72,"Dinâmica dos Fluídos","Somativa2",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(72,"Desenho Técnico","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(72,"Desenho Técnico","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(73,"Automação Indústrial","Somativa1",54);
insert into Notas(RA, disciplina, avaliacao, nota) values(73,"Automação Indústrial","Somativa2",40);
insert into Notas(RA, disciplina, avaliacao, nota) values(73,"Dinâmica dos Fluídos","Somativa1",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(73,"Dinâmica dos Fluídos","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(73,"Desenho Técnico","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(73,"Desenho Técnico","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(74,"Automação Indústrial","Somativa1",58);
insert into Notas(RA, disciplina, avaliacao, nota) values(74,"Automação Indústrial","Somativa2",39);
insert into Notas(RA, disciplina, avaliacao, nota) values(74,"Dinâmica dos Fluídos","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(74,"Dinâmica dos Fluídos","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(74,"Desenho Técnico","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(74,"Desenho Técnico","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(75,"Automação Indústrial","Somativa1",57);
insert into Notas(RA, disciplina, avaliacao, nota) values(75,"Automação Indústrial","Somativa2",38);
insert into Notas(RA, disciplina, avaliacao, nota) values(75,"Dinâmica dos Fluídos","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(75,"Dinâmica dos Fluídos","Somativa2",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(75,"Desenho Técnico","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(75,"Desenho Técnico","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(76,"Automação Indústrial","Somativa1",56);
insert into Notas(RA, disciplina, avaliacao, nota) values(76,"Automação Indústrial","Somativa2",37);
insert into Notas(RA, disciplina, avaliacao, nota) values(76,"Dinâmica dos Fluídos","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(76,"Dinâmica dos Fluídos","Somativa2",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(76,"Desenho Técnico","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(76,"Desenho Técnico","Somativa2",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(77,"Automação Indústrial","Somativa1",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(77,"Automação Indústrial","Somativa2",36);
insert into Notas(RA, disciplina, avaliacao, nota) values(77,"Dinâmica dos Fluídos","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(77,"Dinâmica dos Fluídos","Somativa2",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(77,"Desenho Técnico","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(77,"Desenho Técnico","Somativa2",99);
insert into Notas(RA, disciplina, avaliacao, nota) values(78,"Automação Indústrial","Somativa1",54);
insert into Notas(RA, disciplina, avaliacao, nota) values(78,"Automação Indústrial","Somativa2",35);
insert into Notas(RA, disciplina, avaliacao, nota) values(78,"Dinâmica dos Fluídos","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(78,"Dinâmica dos Fluídos","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(78,"Desenho Técnico","Somativa1",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(78,"Desenho Técnico","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(79,"Automação Indústrial","Somativa1",53);
insert into Notas(RA, disciplina, avaliacao, nota) values(79,"Automação Indústrial","Somativa2",34);
insert into Notas(RA, disciplina, avaliacao, nota) values(79,"Dinâmica dos Fluídos","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(79,"Dinâmica dos Fluídos","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(79,"Desenho Técnico","Somativa1",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(79,"Desenho Técnico","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(80,"Automação Indústrial","Somativa1",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(80,"Automação Indústrial","Somativa2",33);
insert into Notas(RA, disciplina, avaliacao, nota) values(80,"Dinâmica dos Fluídos","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(80,"Dinâmica dos Fluídos","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(80,"Desenho Técnico","Somativa1",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(80,"Desenho Técnico","Somativa2",92);
insert into Notas(RA, disciplina, avaliacao, nota) values(81,"Automação Indústrial","Somativa1",69);
insert into Notas(RA, disciplina, avaliacao, nota) values(81,"Automação Indústrial","Somativa2",32);
insert into Notas(RA, disciplina, avaliacao, nota) values(81,"Dinâmica dos Fluídos","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(81,"Dinâmica dos Fluídos","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(81,"Desenho Técnico","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(81,"Desenho Técnico","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(82,"Automação Indústrial","Somativa1",59);
insert into Notas(RA, disciplina, avaliacao, nota) values(82,"Automação Indústrial","Somativa2",31);
insert into Notas(RA, disciplina, avaliacao, nota) values(82,"Dinâmica dos Fluídos","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(82,"Dinâmica dos Fluídos","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(82,"Desenho Técnico","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(82,"Desenho Técnico","Somativa2",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(83,"Automação Indústrial","Somativa1",58);
insert into Notas(RA, disciplina, avaliacao, nota) values(83,"Automação Indústrial","Somativa2",30);
insert into Notas(RA, disciplina, avaliacao, nota) values(83,"Dinâmica dos Fluídos","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(83,"Dinâmica dos Fluídos","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(83,"Desenho Técnico","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(83,"Desenho Técnico","Somativa2",77);
insert into Notas(RA, disciplina, avaliacao, nota) values(84,"Automação Indústrial","Somativa1",57);
insert into Notas(RA, disciplina, avaliacao, nota) values(84,"Automação Indústrial","Somativa2",10);
insert into Notas(RA, disciplina, avaliacao, nota) values(84,"Dinâmica dos Fluídos","Somativa1",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(84,"Dinâmica dos Fluídos","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(84,"Desenho Técnico","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(84,"Desenho Técnico","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(85,"Automação Indústrial","Somativa1",56);
insert into Notas(RA, disciplina, avaliacao, nota) values(85,"Automação Indústrial","Somativa2",20);
insert into Notas(RA, disciplina, avaliacao, nota) values(85,"Dinâmica dos Fluídos","Somativa1",99);
insert into Notas(RA, disciplina, avaliacao, nota) values(85,"Dinâmica dos Fluídos","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(85,"Desenho Técnico","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(85,"Desenho Técnico","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(86,"Automação Indústrial","Somativa1",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(86,"Automação Indústrial","Somativa2",30);
insert into Notas(RA, disciplina, avaliacao, nota) values(86,"Dinâmica dos Fluídos","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(86,"Dinâmica dos Fluídos","Somativa2",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(86,"Desenho Técnico","Somativa1",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(86,"Desenho Técnico","Somativa2",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(87,"Automação Indústrial","Somativa1",72);
insert into Notas(RA, disciplina, avaliacao, nota) values(87,"Automação Indústrial","Somativa2",40);
insert into Notas(RA, disciplina, avaliacao, nota) values(87,"Dinâmica dos Fluídos","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(87,"Dinâmica dos Fluídos","Somativa2",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(87,"Desenho Técnico","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(87,"Desenho Técnico","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(88,"Automação Indústrial","Somativa1",71);
insert into Notas(RA, disciplina, avaliacao, nota) values(88,"Automação Indústrial","Somativa2",50);
insert into Notas(RA, disciplina, avaliacao, nota) values(88,"Dinâmica dos Fluídos","Somativa1",92);
insert into Notas(RA, disciplina, avaliacao, nota) values(88,"Dinâmica dos Fluídos","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(88,"Desenho Técnico","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(88,"Desenho Técnico","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(89,"Automação Indústrial","Somativa1",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(89,"Automação Indústrial","Somativa2",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(89,"Dinâmica dos Fluídos","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(89,"Dinâmica dos Fluídos","Somativa2",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(89,"Desenho Técnico","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(89,"Desenho Técnico","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(90,"Automação Indústrial","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(90,"Automação Indústrial","Somativa2",70);
insert into Notas(RA, disciplina, avaliacao, nota) values(90,"Dinâmica dos Fluídos","Somativa1",88);
insert into Notas(RA, disciplina, avaliacao, nota) values(90,"Dinâmica dos Fluídos","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(90,"Desenho Técnico","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(90,"Desenho Técnico","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(91,"Automação Indústrial","Somativa1",78);
insert into Notas(RA, disciplina, avaliacao, nota) values(91,"Automação Indústrial","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(91,"Dinâmica dos Fluídos","Somativa1",77);
insert into Notas(RA, disciplina, avaliacao, nota) values(91,"Dinâmica dos Fluídos","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(91,"Desenho Técnico","Somativa1",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(91,"Desenho Técnico","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(92,"Automação Indústrial","Somativa1",77);
insert into Notas(RA, disciplina, avaliacao, nota) values(92,"Automação Indústrial","Somativa2",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(92,"Dinâmica dos Fluídos","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(92,"Dinâmica dos Fluídos","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(92,"Desenho Técnico","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(92,"Desenho Técnico","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(93,"Automação Indústrial","Somativa1",76);
insert into Notas(RA, disciplina, avaliacao, nota) values(93,"Automação Indústrial","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(93,"Dinâmica dos Fluídos","Somativa1",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(93,"Dinâmica dos Fluídos","Somativa2",79);
insert into Notas(RA, disciplina, avaliacao, nota) values(93,"Desenho Técnico","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(93,"Desenho Técnico","Somativa2",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(94,"Automação Indústrial","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(94,"Automação Indústrial","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(94,"Dinâmica dos Fluídos","Somativa1",90);
insert into Notas(RA, disciplina, avaliacao, nota) values(94,"Dinâmica dos Fluídos","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(94,"Desenho Técnico","Somativa1",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(94,"Desenho Técnico","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(95,"Automação Indústrial","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(95,"Automação Indústrial","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(95,"Dinâmica dos Fluídos","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(95,"Dinâmica dos Fluídos","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(95,"Desenho Técnico","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(95,"Desenho Técnico","Somativa2",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(96,"Automação Indústrial","Somativa1",73);
insert into Notas(RA, disciplina, avaliacao, nota) values(96,"Automação Indústrial","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(96,"Dinâmica dos Fluídos","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(96,"Dinâmica dos Fluídos","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(96,"Desenho Técnico","Somativa1",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(96,"Desenho Técnico","Somativa2",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(97,"Automação Indústrial","Somativa1",72);
insert into Notas(RA, disciplina, avaliacao, nota) values(97,"Automação Indústrial","Somativa2",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(97,"Dinâmica dos Fluídos","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(97,"Dinâmica dos Fluídos","Somativa2",80);
insert into Notas(RA, disciplina, avaliacao, nota) values(97,"Desenho Técnico","Somativa1",74);
insert into Notas(RA, disciplina, avaliacao, nota) values(97,"Desenho Técnico","Somativa2",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(98,"Automação Indústrial","Somativa1",71);
insert into Notas(RA, disciplina, avaliacao, nota) values(98,"Automação Indústrial","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(98,"Dinâmica dos Fluídos","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(98,"Dinâmica dos Fluídos","Somativa2",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(98,"Desenho Técnico","Somativa1",84);
insert into Notas(RA, disciplina, avaliacao, nota) values(98,"Desenho Técnico","Somativa2",0);
insert into Notas(RA, disciplina, avaliacao, nota) values(99,"Automação Indústrial","Somativa1",60);
insert into Notas(RA, disciplina, avaliacao, nota) values(99,"Automação Indústrial","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(99,"Dinâmica dos Fluídos","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(99,"Dinâmica dos Fluídos","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(99,"Desenho Técnico","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(99,"Desenho Técnico","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(100,"Automação Indústrial","Somativa1",49);
insert into Notas(RA, disciplina, avaliacao, nota) values(100,"Automação Indústrial","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(100,"Dinâmica dos Fluídos","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(100,"Dinâmica dos Fluídos","Somativa2",81);
insert into Notas(RA, disciplina, avaliacao, nota) values(100,"Desenho Técnico","Somativa1",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(100,"Desenho Técnico","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(101,"Automação Indústrial","Somativa1",48);
insert into Notas(RA, disciplina, avaliacao, nota) values(101,"Automação Indústrial","Somativa2",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(101,"Dinâmica dos Fluídos","Somativa1",55);
insert into Notas(RA, disciplina, avaliacao, nota) values(101,"Dinâmica dos Fluídos","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(101,"Desenho Técnico","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(101,"Desenho Técnico","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(102,"Automação Indústrial","Somativa1",47);
insert into Notas(RA, disciplina, avaliacao, nota) values(102,"Automação Indústrial","Somativa2",65);
insert into Notas(RA, disciplina, avaliacao, nota) values(102,"Dinâmica dos Fluídos","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(102,"Dinâmica dos Fluídos","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(102,"Desenho Técnico","Somativa1",98);
insert into Notas(RA, disciplina, avaliacao, nota) values(102,"Desenho Técnico","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(103,"Automação Indústrial","Somativa1",46);
insert into Notas(RA, disciplina, avaliacao, nota) values(103,"Automação Indústrial","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(103,"Dinâmica dos Fluídos","Somativa1",66);
insert into Notas(RA, disciplina, avaliacao, nota) values(103,"Dinâmica dos Fluídos","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(103,"Desenho Técnico","Somativa1",99);
insert into Notas(RA, disciplina, avaliacao, nota) values(103,"Desenho Técnico","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(104,"Automação Indústrial","Somativa1",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(104,"Automação Indústrial","Somativa2",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(104,"Dinâmica dos Fluídos","Somativa1",45);
insert into Notas(RA, disciplina, avaliacao, nota) values(104,"Dinâmica dos Fluídos","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(104,"Desenho Técnico","Somativa1",100);
insert into Notas(RA, disciplina, avaliacao, nota) values(104,"Desenho Técnico","Somativa2",75);
insert into Notas(RA, disciplina, avaliacao, nota) values(105,"Automação Indústrial","Somativa1",44);
insert into Notas(RA, disciplina, avaliacao, nota) values(105,"Automação Indústrial","Somativa2",85);
insert into Notas(RA, disciplina, avaliacao, nota) values(105,"Dinâmica dos Fluídos","Somativa1",87);
insert into Notas(RA, disciplina, avaliacao, nota) values(105,"Dinâmica dos Fluídos","Somativa2",96);
insert into Notas(RA, disciplina, avaliacao, nota) values(105,"Desenho Técnico","Somativa1",95);
insert into Notas(RA, disciplina, avaliacao, nota) values(105,"Desenho Técnico","Somativa2",75);

select * from Alunos;
select * from Notas;
describe Alunos;
describe Notas;
show tables;